[tool.pytest.ini_options]
addopts = "-q --cov=core --cov-report=term-missing --cov-report=xml"
DJANGO_SETTINGS_MODULE = "newfarm.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
markers = [
  "webhook: tests that require webhook module",
]