# Generated by Django 5.2.6 on 2025-09-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=200, null=True)),
                ('is_live_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
