# Generated by Django 5.2.6 on 2025-09-18 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='schedule_dogs',
            field=models.IntegerField(help_text='Number of dogs to be walked during this service (minimum 1)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='schedule_location',
            field=models.CharField(blank=True, help_text='Full address where the dog walking service will be provided', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='schedule_notes',
            field=models.TextField(blank=True, help_text='Additional notes or special instructions for the dog walker', null=True),
        ),
    ]
