# Generated by Django 5.2.6 on 2025-09-20 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stripesettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_dt', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('credit_cents', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=200)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=200)),
                ('service_label', models.CharField(max_length=200)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('dogs', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=50)),
                ('price_cents', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(default='dog', max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('meds', models.TextField(blank=True)),
                ('behaviour', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet')),
            ],
            options={
                'unique_together': {('booking', 'pet')},
            },
        ),
    ]
