# Generated by Django 5.2.6 on 2025-09-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminevent_client_suboccurrence_booking_pet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='meds',
            new_name='medications',
        ),
        migrations.AddField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
