# Generated by Django 5.2.6 on 2025-09-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_actual_clients_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_secret_key', models.CharField(blank=True, help_text='Stripe Secret Key (sk_test_... or sk_live_...)', max_length=200, null=True)),
                ('is_live_mode', models.BooleanField(default=False, help_text='Automatically determined based on key prefix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stripe Settings',
                'verbose_name_plural': 'Stripe Settings',
            },
        ),
    ]
