# Generated by Django 5.2.6 on 2025-09-24 06:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeKeyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('previous_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('new_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('previous_test_or_live', models.CharField(blank=True, max_length=16, null=True)),
                ('new_test_or_live', models.CharField(blank=True, max_length=16, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
    ]
