# Generated by Django 5.2.7 on 2025-10-07 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stripekeyaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=64, unique=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service defaults',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='block_label',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='can_self_reschedule',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TimetableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'start_time', 'end_time', 'label')},
            },
        ),
        migrations.CreateModel(
            name='CapacityHold',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_code', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timetableblock')),
            ],
            options={
                'verbose_name_plural': 'Capacity holds',
            },
        ),
        migrations.CreateModel(
            name='BlockCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=64)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('allow_overlap', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='core.timetableblock')),
            ],
            options={
                'verbose_name_plural': 'Block capacities',
                'unique_together': {('block', 'service_code')},
            },
        ),
    ]
