# Generated by Django 5.2.7 on 2025-10-12 02:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscriptionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=64, unique=True)),
                ('service_code', models.CharField(max_length=64)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subs', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscriptionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays_csv', models.CharField(help_text='e.g. mon,tue,wed', max_length=64)),
                ('default_time', models.CharField(help_text='HH:MM local time (AEST).', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{2}:\\d{2}$')])),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('default_block_label', models.CharField(blank=True, max_length=128, null=True)),
                ('last_materialized_until', models.DateField(blank=True, null=True)),
                ('sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.stripesubscriptionlink')),
            ],
        ),
    ]
