# Generated by Django 5.2.7 on 2025-10-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_stripe_subscription_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suboccurrence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suboccurrence',
            name='stripe_subscription_id',
            field=models.CharField(max_length=64),
        ),
    ]
