# Generated by Django 5.2.6 on 2025-10-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_suboccurrence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_key',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
