# Generated by Django 5.2.6 on 2025-10-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_booking_external_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=16,
                                   choices=[('unpaid','Unpaid'),('paid','Paid'),('void','Voided'),('failed','Failed')]),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
