# Generated by Django 5.2.6 on 2025-10-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_service_to_suboccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscriptionlink',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionlink',
            name='time_of_day',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionlink',
            name='weekday',
            field=models.IntegerField(blank=True, help_text='0=Mon ... 6=Sun', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
