# Generated by Django 5.2.6 on 2025-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_stripesubscriptionlink_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscriptionschedule',
            name='days',
            field=models.CharField(blank=True, help_text='Comma-separated: MON,TUE,...', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionschedule',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionschedule',
            name='repeats',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly')], default='weekly', max_length=16),
        ),
        migrations.AddField(
            model_name='stripesubscriptionschedule',
            name='start_time',
            field=models.CharField(blank=True, help_text='HH:MM (24h)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionschedule',
            name='visits_per_fortnight',
            field=models.PositiveIntegerField(blank=True, help_text='Informational only', null=True),
        ),
    ]
