# Generated by Django 5.2.6 on 2025-10-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_repeats_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requires_admin_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_diff',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_source_invoice_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
