from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_booking_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="schedule",
            field=models.ForeignKey(
                to="core.stripesubscriptionschedule",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name="bookings",
                help_text="Owning subscription schedule for auto-generated bookings."
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="autogenerated",
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]
