# Generated by Django 5.2.6 on 2025-10-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_service_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicewindow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
