name: Bug report
description: File a bug
title: "[Bug] <short title>"
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      value: |
        1. Go to ...
        2. Click ...
        3. See error ...
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - S0-Blocker
        - S1-Critical
        - S2-Major
        - S3-Minor
